/*
Deployment script for C:\USERS\PLIVI\DOCUMENTS\GRAPHISOFT TESZT FELADAT\FULLSTACKDEV\WEBSHOPADMIN\APP_DATA\WEBSHOP_INIT.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\PLIVI\DOCUMENTS\GRAPHISOFT TESZT FELADAT\FULLSTACKDEV\WEBSHOPADMIN\APP_DATA\WEBSHOP_INIT.MDF"
:setvar DefaultFilePrefix "C_\USERS\PLIVI\DOCUMENTS\GRAPHISOFT TESZT FELADAT\FULLSTACKDEV\WEBSHOPADMIN\APP_DATA\WEBSHOP_INIT.MDF_"
:setvar DefaultDataPath "C:\Users\plivi\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\plivi\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[product_categories]...';


GO
CREATE TABLE [dbo].[product_categories] (
    [Id]   INT        NOT NULL,
    [name] NCHAR (10) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[products]...';


GO
CREATE TABLE [dbo].[products] (
    [Id]          INT        NOT NULL,
    [category]    INT        NOT NULL,
    [name]        NCHAR (10) NOT NULL,
    [description] NCHAR (10) NULL,
    [price]       MONEY      NOT NULL,
    [owner_name]  NCHAR (10) NOT NULL,
    [email]       NCHAR (10) NOT NULL,
    [created_on]  TIMESTAMP  NOT NULL,
    [updated_on]  DATETIME   NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[products]...';


GO
ALTER TABLE [dbo].[products]
    ADD DEFAULT 0 FOR [category];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
